name: Docker Image CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Npm Install
      run: npm i
    - name: Npm Build
      run: npm run build
    - name: Test
      run: ls
    - name: Docker Push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: eux86/mc-discord-bot
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


